### PR TITLE
Fix spacing and font size of inserted headers

### LINKED ISSUE #160: Missing settings in v3.0.0
Version 3.0.0 is missing a lot of the features and settings from 2.6.0. Is that intended? The reply headers look worse now and I'd like to fix that but can't really because the font size for example cannot be set anymore.

Also, all settings were reset with the new version. I guess that's because the settings are so incompatible and lacking.

The Thunderbird 128 upgrade caught me by surprise. Now I have to clean up the mess it created – again. I still have v115 on my laptop so I can at least compare what went wrong in the new version.

v2.6.0:
grafik

v3.0.0:
grafik

### PR DESCRIPTION
**Pull request by ygoe**
- Added missing empty line between reply headers and reply body
- Aligned line space before and after headers for reply and forward
- Removed wrong font-size style from inserted content
- Simplified CSS length units

Fixes #160

### CODE REVIEW

File: modules/compose.mjs [hunk 1]
```diff
@@ -16,10 +16,11 @@ import * as rwhAccounts from './accounts.mjs';
 import * as rwhUtils from './utils.mjs';
 
 const positionBeforeBegin = 'beforebegin';
+const positionBeforeEnd = 'beforeend';
 const positionAfterBegin = 'afterbegin';
 const fwdHdrLookupString = '-------- ';
 const plainTextFirstChars = '> ';
-const cleanBlockQuoteStyle = 'border:none !important; padding-left:0px !important; margin-left:0px !important;';
+const cleanBlockQuoteStyle = 'border:none !important; padding-left:0 !important; margin-left:0 !important;';
```
Comment (jeevatkm) [inline modules/compose.mjs:23]: @ygoe Initially, it was unitless. The user reported that it did not work with other email clients (Apple Mail, Outlook), so I had to add it.

File: modules/compose.mjs [hunk 2]
```diff
@@ -192,7 +195,15 @@ class ReplyWithHeader {
...
-            mozForwardContainer.insertAdjacentElement(positionAfterBegin, this._createElement('br'));
+			
+			// Insert 2 <br> before the headers to make it look like a reply does.
+			mozForwardContainer.insertAdjacentElement(positionAfterBegin, this._createElement('br'));
+			mozForwardContainer.insertAdjacentElement(positionAfterBegin, this._createElement('br'));
+
+			// There are 2 <br> originally, but none for reply mode.
+			// We add one for replies, so let's remove one for forwards to make it even.
+			let nextBr = mozForwardContainer.querySelector("div.moz-email-headers-table + br");
+			nextBr?.remove();
```
Comment (jeevatkm) [inline modules/compose.mjs:206]: @ygoe Can you please format this code block correctly?

I'm okay with adding a new `br,` but let's remove these lines from 203 to 206. TB does not always play well.

File: modules/compose.mjs [hunk 3]
```diff
@@ -267,7 +278,7 @@ class ReplyWithHeader {
         let rwhHeaders = '<div id="rwhHeaders"';
         if (await rwhSettings.isHeaderHtmlPrefixLine()) {
             let borderColor = await rwhSettings.getHeaderHtmlPrefixLineColor();
-            rwhHeaders += ` style="border:none;border-top:solid ${borderColor} 1.0pt;padding:3.0pt 0cm 0cm 0cm"`
+            rwhHeaders += ` style="border-top:solid ${borderColor} 1px;padding-top:3px"`
```
Comment (jeevatkm) [inline modules/compose.mjs:281]: @ygoe I obtained this `style` code from the Outlook mail client. It works on all email clients for some reason; unit `px` does not always work. So far, my understanding is that HTML CSS style(s) on email content interferes with unit `px` a lot. 

Also, it is good to reset and set the style you need when overriding eg.: `border:none;border-top:solid...`

File: modules/compose.mjs [hunk 4]
```diff
@@ -282,12 +293,12 @@ class ReplyWithHeader {
             }
 
             if (headers[hdrKey]) {
-                rwhHeaders += '<p style="margin:0cm;font-size:11.5pt"><span><b>' + lbl + '</b> ' + headers[hdrKey] + '</span></p>';
+                rwhHeaders += '<p style="margin:0"><span><b>' + lbl + '</b> ' + headers[hdrKey] + '</span></p>';
```
Comment (jeevatkm) [inline modules/compose.mjs:296]: @ygoe I can't recall why I added `font-size:11.5pt`, but I'm sure there is a reason.
I obtained this from an Outlook client. I'm okay with removing the font-size value (we can wait for user feedback later). But preserve the margin with units either `0cm` or `0px`, whichever you prefer. Typically, unit less works well on webpages than email client HTML rendering.

File: modules/compose.mjs [hunk 5]
```diff
@@ -477,7 +488,7 @@ class ReplyWithHeader {
             } else {
                 let rwhHeaders = '';
                 for (let [key, value] of Object.entries(remainingHeaders)) {
-                    rwhHeaders += '<p style="margin:0cm;font-size:11.5pt"><span><b>'
+                    rwhHeaders += '<p style="margin:0"><span><b>'
```
Comment (jeevatkm) [inline modules/compose.mjs:491]: @ygoe Please refer to the above comment.

**Review by jeevatkm — CHANGES_REQUESTED** [review]
@ygoe Thanks for your PR. I have added some review feedback; please have a look.

**Comment by jeevatkm** [comment]
@ygoe Did you get a chance to look at the PR comments?

File: modules/compose.mjs (hunk 1 above)
Comment (ygoe) [reply modules/compose.mjs:23]: Okay, I'm adding the units back. I didn't have that info. Maybe a comment in the code could make it clear to other readers as well so this information doesn't get lost.

File: modules/compose.mjs (hunk 2 above)
Comment (ygoe) [reply modules/compose.mjs:206]: What's to format here? Looks good to me. Please clarify.

I've changed the brs so that it matches exactly, line by line, the behaviour of Thunderbird without this add-on, for both reply and forward. So I was actually minimising the distortions this add-on introduces.

What does "play well" mean here? What would it do when what was expected? I don't have any information on that, and I've successfully tested this in the only supported version of Thunderbird.

File: modules/compose.mjs (hunk 3 above)
Comment (ygoe) [reply modules/compose.mjs:281]: I have reverted all style optimisations here. Although I've never experienced issues with the px unit in e-mails. Actually I see it a lot in extensively formatted e-mails I get, including for example Stackoverflow notifications.

File: modules/compose.mjs (hunk 4 above)
Comment (ygoe) [reply modules/compose.mjs:296]: That's the main point, this font-size is wrong and needs to go away. It sets the font to something else than the default size and it's also a size that cannot even be selected by the user. If this is new to you, consider this one of that feedback you got on other compatibility issues. And setting the size is also unnecessary because none of the other text has one. And that is precisely how to get the default font size: don't set any.

I have reverted the style optimisation here but left out the font-size. Without it, my PR is pointless.

File: modules/compose.mjs (hunk 5 above)
Comment (ygoe) [reply modules/compose.mjs:491]: Same as above.

File: modules/compose.mjs (hunk 1 above)
Comment (jeevatkm) [reply modules/compose.mjs]: Thanks @ygoe

File: modules/compose.mjs (hunk 4 above)
Comment (jeevatkm) [reply modules/compose.mjs]: I appreciate your understanding. People use various email clients, and RWH users report that their emails are displayed incorrectly on the receiver side.
Even the old Thunderbird client (before TB started using Firefox as the base) used to have email rendering issues and differences.

As I mentioned before, we can remove the font-size and see if any users get back to me with an issue. Then I will figure out how to fix it.

File: modules/compose.mjs (hunk 2 above)
Comment (ygoe) [reply modules/compose.mjs:205]: Maybe without a signature it's different? I have one. And I admit I haven't tested without a signature.

File: modules/compose.mjs (hunk 4 above)
Comment (ygoe) [reply modules/compose.mjs]: Okay. I was also looking at the actually generated HTML (save as draft and view source of that message) to inspect things. There's no font-size anywhere within the regular content or Thunderbird's own reply or forward headers. So I wonder how adding one would fix anything.

File: modules/compose.mjs (hunk 2 above)
Comment (jeevatkm) [reply modules/compose.mjs:205]: @ygoe I'm sorry, but I forgot to mention the code format. Your new code lines have an additional tab in them; kindly align it with the `if` block code alignment.

Please remove these lines from 203 to 206.

**Review by jeevatkm — CHANGES_REQUESTED** [review]

**Comment by jeevatkm** [comment]
@ygoe, any update on removing lines from 203 to 206? Then, we can merge the PR.

**Comment by jeevatkm** [comment]
@ygoe, I will merge your PR and update it as required.

**Review by jeevatkm — APPROVED** [review]
